#!/usr/bin/env python3
"""
train.py — Unified Brainfuck SLM Training Pipeline
====================================================

Builds a character-level bigram or trigram transition table from a text
corpus and emits a Brainfuck program that acts as an autoregressive
language model.

Usage:
    # Bigram (default)
    python3 train.py --corpus-file corpus/english.txt
    python3 train.py --corpus-file corpus/english.txt --mode bigram --steps 20 -o slm.bf

    # Trigram with temperature
    python3 train.py --corpus-file corpus/pidgin.txt --mode trigram -o slm_pidgin.bf
    python3 train.py --corpus-file corpus/pidgin.txt --mode trigram --candidates 5 --steps 60

    # Inline corpus (no file needed)
    python3 train.py --corpus "the cat sat on the mat " --mode bigram

The generated BF program:
  Bigram:  reads seed char, predicts next via bigram table, repeats N steps
  Trigram: reads 2-char seed, predicts via trigram table + entropy, repeats N steps
"""

import argparse
import re
import sys
from collections import Counter, defaultdict


# ═══════════════════════════════════════════════════════════════════
#  BIGRAM MODEL
# ═══════════════════════════════════════════════════════════════════

def build_bigram_table(corpus: str) -> dict[str, str]:
    """Build {char: most_likely_next_char} from corpus."""
    bigram_counts: dict[str, Counter] = {}
    for i in range(len(corpus) - 1):
        current = corpus[i]
        nxt = corpus[i + 1]
        if current not in bigram_counts:
            bigram_counts[current] = Counter()
        bigram_counts[current][nxt] += 1
    return {char: followers.most_common(1)[0][0] for char, followers in bigram_counts.items()}


def simulate_bigram(table: dict[str, str], seed: str, steps: int = 20) -> str:
    """Simulate bigram generation for verification."""
    result = [seed]
    current = seed
    for _ in range(steps):
        nxt = table.get(current, " ")
        result.append(nxt)
        current = nxt
    return "".join(result)


# ═══════════════════════════════════════════════════════════════════
#  TRIGRAM MODEL
# ═══════════════════════════════════════════════════════════════════

# Entropy period: use 11 (prime) so loops of common lengths don't align
ENTROPY_MAX = 11


def build_trigram_table(corpus: str, max_candidates: int = 3):
    """Build trigram table with up to max_candidates per pair.
    Returns {(c1, c2): [(next_char, count), ...]}"""
    counts: dict[tuple, Counter] = defaultdict(Counter)
    for i in range(len(corpus) - 2):
        counts[(corpus[i], corpus[i + 1])][corpus[i + 2]] += 1
    return {k: v.most_common(max_candidates) for k, v in counts.items()}


def simulate_trigram(table: dict, s1: str, s2: str, steps: int = 60) -> str:
    """Simulate trigram generation for verification."""
    c1, c2, ent, out = s1, s2, 0, []
    for _ in range(steps):
        cands = table.get((c1, c2))
        if not cands:
            nxt = " "
        elif len(cands) == 1:
            nxt = cands[0][0]
        else:
            K = len(cands)
            idx = sum(1 for i in range(1, K) if ent >= i * ENTROPY_MAX // K)
            idx = min(idx, K - 1)
            nxt = cands[idx][0]
        out.append(nxt)
        c1, c2 = c2, nxt
        ent = (ent + 1) % ENTROPY_MAX
    return "".join(out)


# ═══════════════════════════════════════════════════════════════════
#  BRAINFUCK CODE GENERATION (shared)
# ═══════════════════════════════════════════════════════════════════

def bf(val: int) -> str:
    """Generate BF to set current cell = val."""
    if val == 0:
        return "[-]"
    parts = ["[-]"]
    v = val
    while v > 0:
        parts.append("+" * min(v, 10))
        v -= min(v, 10)
    return "".join(parts)


# ── Bigram BF generation ──────────────────────────────────────────

def generate_bigram_program(table: dict[str, str], steps: int = 20) -> str:
    """Generate BF program using bigram transitions.

    Tape layout:
      cell 0 = iteration counter
      cell 1 = current character
      cell 2 = comparison copy
      cell 3 = comparison target
      cell 4 = match flag
      cell 5 = predicted next character
      cell 6 = copy temp
    """
    vocab = sorted(c for c in table.keys() if 32 <= ord(c) <= 126)
    lines = []

    lines.append("; Brainfuck SLM - Bigram Model")
    lines.append("; Generated by train.py")
    lines.append(";")
    lines.append(f"; Vocab: {' '.join(repr(c) for c in vocab)}")

    # Init
    lines.append("; === INIT ===")
    lines.append(bf(steps))
    lines.append("> ,")
    lines.append("<")

    # Main loop
    lines.append("")
    lines.append(f"; === GENERATION LOOP ({steps} iterations) ===")
    lines.append("[")
    lines.append("  -")

    for v in vocab:
        p = table[v]
        V, P = ord(v), ord(p)
        lines.append(f"  ; '{v}' (ord={V}) -> '{p}' (ord={P})")
        lines.append("  >")
        lines.append("  [- >+ >>>>+ <<<<<]")
        lines.append("  >>>>>[-<<<<<+>>>>>]<<<<<")
        lines.append(f"  >>{bf(V)}<<")
        lines.append("  >[- >- <]")
        lines.append("  >>[-]+<<")
        lines.append("  [- >>[-]<< [-]]")
        lines.append("  >[- >[-]< [-]]")
        lines.append(f"  >[- >[-]{bf(P)}<]")
        lines.append("  <<<<")
        lines.append("")

    # Move prediction to cell 1, output
    lines.append("  ; Clear cell 1 and move prediction from cell 5")
    lines.append("  >[-] >>>>[-<<<<+>>>>]")
    lines.append("  <<<<.")
    lines.append("  <")
    lines.append("]")
    lines.append("; === END ===")

    return "\n".join(lines)


# ── Trigram BF generation ─────────────────────────────────────────

def gen_trigram_block(t1: str, t2: str, cands: list) -> list[str]:
    """Generate one trigram comparison block. Pointer at cell0 in, cell0 out.

    Tape: 0=ctr 1=c1 2=c2 3=comp 4=tgt 5=tmp 6=flag 7=pred
          8=entropy 9=tA 10=tB 11=ovr
    """
    V1, V2 = ord(t1), ord(t2)
    K = len(cands)
    P0 = ord(cands[0][0])
    L = []

    # FLAG=1 (cell6)
    L.append(">>>>>>[-]+<<<<<<")

    # COPY cell1->cell3 via cell5 (preserve cell1)
    L.append(">[- >>+ >>+ <<<<]>>>>[-<<<<+>>>>]<<")

    # SET cell4=V1, COMPARE cell3 vs cell4
    L.append(f">{bf(V1)}")
    L.append("<[- >- <]")
    L.append("[- >>>[-]<<< [-]]")
    L.append(">[- >>[-]<< [-]]")

    # COPY cell2->cell3 via cell5 (preserve cell2)
    L.append("<<[- >+ >>+ <<<]>>>[-<<<+>>>]<<")

    # SET cell4=V2, COMPARE
    L.append(f">{bf(V2)}")
    L.append("<[- >- <]")
    L.append("[- >>>[-]<<< [-]]")
    L.append(">[- >>[-]<< [-]]")

    # NAVIGATE TO FLAG (cell6)
    L.append(">>")

    # IF FLAG=1, SELECT PREDICTION
    if K == 1:
        L.append("[-")
        L.append(f">{bf(P0)}")
        L.append("<")
        L.append("]")
        L.append("<<<<<<")
        return L

    # Multi-candidate: default P0, then entropy overrides
    L.append("[-")                   # if flag≠0. cell6→0
    L.append(">[-]")                 # cell7=0
    L.append(f"{bf(P0)}")           # cell7=P0

    for i in range(1, K):
        Pi = ord(cands[i][0])
        thr = i * ENTROPY_MAX // K

        L.append(f"; entropy>={thr} -> '{cands[i][0]}'")
        L.append(">")                # 7→8

        # Clear stale data, then COPY cell8→cell9 via cell10
        L.append(">[-]>[-]<<")       # cell9=0, cell10=0
        L.append("[- >+ >+ <<]")    # cell8→cell9, cell10
        L.append(">>[- <<+ >>]")     # restore cell8

        # SET cell11=1 (override flag)
        L.append(">[-]+")           # cell11=1

        # SET cell10=threshold
        L.append("<")
        L.append(f"{bf(thr)}")

        # COMPARE cell9 vs cell10
        L.append("<")
        L.append("[- >- <]")

        # IF cell10>0 (entropy<thr): clear cell11
        L.append(">")
        L.append("[- >[-] <]")

        # CHECK cell11 (override?)
        L.append(">")
        L.append("[-")
        L.append("<<<<")
        L.append("[-]")
        L.append(f"{bf(Pi)}")
        L.append(">>>>")
        L.append("]")

        # BACK to cell7
        L.append("<<<<")

    # Close flag block
    L.append("<")
    L.append("]")
    L.append("<<<<<<")

    return L


def generate_trigram_program(table: dict, steps: int = 60) -> str:
    """Generate full BF program using trigram transitions + entropy."""
    trigrams = {
        k: v for k, v in table.items()
        if all(32 <= ord(c) <= 126 for c in (k[0], k[1]))
        and all(32 <= ord(c[0]) <= 126 for c in v)
    }
    st = sorted(trigrams.items())

    L = []
    L.append("; Brainfuck SLM - Trigram Model with Temperature")
    L.append("; Generated by train.py")
    L.append("; Tape: 0=ctr 1=c1 2=c2 3=comp 4=tgt 5=tmp 6=flag 7=pred 8=ent 9=tA 10=tB 11=ovr")

    # INIT
    L.append(bf(steps))
    L.append(">,>,<<")

    # MAIN LOOP
    L.append("[")
    L.append("  -")
    L.append("")

    for (t1, t2), cands in st:
        L.extend(gen_trigram_block(t1, t2, cands))
        L.append("")

    # SHIFT: c1<-c2, c2<-prediction
    L.append("  ; shift")
    L.append("  >[-]")
    L.append("  >[-<+>]<")
    L.append("  >>>>>>[-<<<<<+>>>>>]")
    L.append("  <<<<<<<")

    # OUTPUT
    L.append("  >>.<<")

    # ENTROPY: increment, reset if >= ENTROPY_MAX
    L.append("  ; entropy")
    L.append("  >>>>>>>>")
    L.append("  +")
    L.append("  >[-]>[-]<<")
    L.append("  [- >+ >+ <<]")
    L.append("  >>[- <<+ >>]")
    L.append(f"  {bf(ENTROPY_MAX)}")
    L.append("  <[- >- <]")
    L.append("  >>[-]+")
    L.append("  <")
    L.append("  [- >[-] <]")
    L.append("  >")
    L.append("  [- <<<[-] >>>]")
    L.append("  <<<")
    L.append("  <<<<<<<<")

    L.append("]")
    L.append("; END")
    return "\n".join(L)


# ═══════════════════════════════════════════════════════════════════
#  MAIN
# ═══════════════════════════════════════════════════════════════════

def main():
    parser = argparse.ArgumentParser(
        description="Train a Brainfuck SLM (bigram or trigram) from a text corpus"
    )
    parser.add_argument("--corpus", type=str, help="Inline training corpus text")
    parser.add_argument("--corpus-file", type=str, help="Path to corpus text file")
    parser.add_argument("-m", "--mode", choices=["bigram", "trigram"], default="bigram",
                        help="Model mode: bigram or trigram (default: bigram)")
    parser.add_argument("-k", "--candidates", type=int, default=3,
                        help="Max candidates per trigram context (default: 3)")
    parser.add_argument("-s", "--steps", type=int, default=None,
                        help="Generation steps (default: 20 for bigram, 60 for trigram)")
    parser.add_argument("-o", "--output", type=str, default=None,
                        help="Output BF file (default: slm.bf or slm_pidgin.bf)")
    parser.add_argument("--verify", action="store_true",
                        help="Print verification of the model")
    args = parser.parse_args()

    # Load corpus
    if args.corpus_file:
        with open(args.corpus_file, "r") as f:
            corpus = f.read()
    elif args.corpus:
        corpus = args.corpus
    else:
        print("Error: provide --corpus or --corpus-file", file=sys.stderr)
        sys.exit(1)

    # Defaults
    if args.steps is None:
        args.steps = 60 if args.mode == "trigram" else 20
    if args.output is None:
        args.output = "slm_pidgin.bf" if args.mode == "trigram" else "slm.bf"

    # Build model
    if args.mode == "bigram":
        table = build_bigram_table(corpus)
        print(f"Corpus: {len(corpus)} chars, {len(table)} bigrams", file=sys.stderr)
        print(f"\nBigram transitions:", file=sys.stderr)
        for char in sorted(table.keys()):
            if 32 <= ord(char) <= 126:
                print(f"  '{char}' -> '{table[char]}' (ord {ord(char)} -> {ord(table[char])})", file=sys.stderr)

        if args.verify:
            print(f"\nSimulated outputs:", file=sys.stderr)
            for seed in ["t", "c", "d", "s", "p"]:
                gen = simulate_bigram(table, seed, args.steps)
                print(f"  seed='{seed}' -> \"{gen}\"", file=sys.stderr)

        program = generate_bigram_program(table, args.steps)

    else:  # trigram
        table = build_trigram_table(corpus, args.candidates)
        multi = sum(1 for v in table.values() if len(v) > 1)
        print(f"Corpus: {len(corpus)} chars, {len(table)} trigrams, {multi} multi-cand", file=sys.stderr)

        freq_pairs = sorted(table.items(), key=lambda x: -sum(c for _, c in x[1]))[:20]
        print(f"\nTop 20 frequent pairs:", file=sys.stderr)
        for (t1, t2), cands in freq_pairs:
            total = sum(c for _, c in cands)
            cand_str = ", ".join(f"'{c}'({n})" for c, n in cands)
            print(f"  '{t1}{t2}' [{total}]: {cand_str}", file=sys.stderr)

        if args.verify:
            seeds = [
                ("w", "e"), ("d", "e"), (" ", "d"), ("n", "o"), ("f", "o"),
                ("i", " "), ("a", "b"), ("m", "a"), ("g", "o"), ("i", "g"),
            ]
            print(f"\nSimulated outputs:", file=sys.stderr)
            for s1, s2 in seeds:
                g = simulate_trigram(table, s1, s2, args.steps)
                print(f"  '{s1}{s2}' -> \"{s1}{s2}{g}\"", file=sys.stderr)

        program = generate_trigram_program(table, args.steps)

    # Write output
    with open(args.output, "w") as f:
        f.write(program)

    ic = len(re.findall(r"[><+\-.,\[\]]", program))
    print(f"\nWrote {args.output}: {ic} BF instructions", file=sys.stderr)


if __name__ == "__main__":
    main()
